# Styleguide based on airbnb's guide: https://github.com/airbnb/javascript
---
  extends: "airbnb"
  root: true
  ecmaFeatures:
    jsx: true
    templateStrings: true
    classes: true
    modules: true
  parser: "babel-eslint"
  globals:
    - process
  plugins:
    - react
    - spellcheck
    - inflection
  settings:
    import/resolver:
      babel-module:
      webpack:
  rules:
    no-magic-numbers:
      - 2
      -
        ignoreArrayIndexes: true
        ignore:
          - 0
          - 1
    valid-jsdoc:
      - 2
    no-alert:
      - 2
    no-console:
      - 2
    no-return-assign:
      - 0
    react/jsx-no-bind:
    - 2
    -
      ignoreRefs: true
    no-debugger:
      - 2
    no-underscore-dangle:
      - error
      - allow:
        - __injectIntl
    import/no-extraneous-dependencies:
      - 2
      - devDependencies:
        - "**/*.spec.js"
        - "./scripts/**/*"
        - "./config/**/*"
    inflection/no-plural-filenames:
      - error
    spellcheck/spell-checker:
      - 2
      - comments: true
        strings: true
        identifiers: true
        lang: en_US
        skipWords:
        - a11y
        - api
        - camelize
        - cldr
        - com
        - commonjs
        - concat
        - const
        - diff
        - domchristie
        - filename
        - formatjs
        - github
        - http
        - https
        - iilei
        - javascript
        - js
        - lang
        - mkdirp
        - msg
        - namespace
        - ret
        - src
        - stringify
        - therefor
        - util
        - utils
        - yaml
        - yamljs
        skipIfMatch:
        - http://[^s]*
        - ^\D[^aeiouAEIOU]{2,3}$    # Intl
        - ^\D[^aeiouAEIOU]{1,2}\d+$ # es6
        - ^\D{1,2}\d+\D{1,2}$       # a11y, i18n
        - ^\D{1,2}$                 # fs
