# Styleguide based on airbnb's guide: https://github.com/airbnb/javascript
---
  extends: "airbnb"
  root: true
  ecmaFeatures:
    jsx: true
    templateStrings: true
    classes: true
    modules: true
  parser: "babel-eslint"
  globals:
    process: false
    appConfig: false
    React: false
  no-undef:
    - error
  env:
    browser: true
  plugins:
    - react
    - inflection
    - getsentry
  settings:
    import/resolver:
      babel-module:
      webpack:
  rules:
    react/react-in-jsx-scope: # is exposed
      - 0
    getsentry/jsx-needs-i18n:
      - 1
    no-magic-numbers:
      - error
      -
        ignoreArrayIndexes: true
        ignore:
          - 0
          - 1
    valid-jsdoc:
      - error
    no-alert:
      - error
    no-console:
      - error
    no-return-assign:
      - 0
    react/jsx-no-bind:
      - error
      -
        ignoreRefs: true
    no-debugger:
      - error
    no-underscore-dangle:
      - error
      - allow:
        - __injectIntl
        - __appName
    import/no-extraneous-dependencies:
      - error
      - devDependencies:
        - "**/*.config.js"
        - "**/*.spec.{js,jsx}"
        - "./scripts/**/*"
        - "./config/**/*"
        - "./jestsetup.js"
        - "./webpack.config*"
    inflection/no-plural-filenames:
      - error
    react/prefer-stateless-function:
      - 1
    arrow-parens:
    - 2
    - as-needed
    - requireForBlockBody: true
