# Styleguide based on airbnb's guide: https://github.com/airbnb/javascript
---
  extends: "airbnb"
  root: true
  ecmaFeatures:
    jsx: true
    templateStrings: true
    classes: true
    modules: true
  parser: "babel-eslint"
  globals:
    - process
  plugins:
    - react
    - spellcheck
    - inflection
  settings:
    import/resolver:
      babel-module:
      webpack:
  rules:
    no-magic-numbers:
      - 2
      -
        ignoreArrayIndexes: true
        ignore:
          - 0
          - 1
    valid-jsdoc:
      - 2
    no-alert:
      - 2
    no-console:
      - 2
    no-return-assign:
      - 0
    react/jsx-no-bind:
    - 2
    -
      ignoreRefs: true
    no-debugger:
      - 2
    no-underscore-dangle:
      - error
      - allow:
        - __injectIntl
    import/no-extraneous-dependencies:
      - 2
      - devDependencies:
        - "**/*.spec.js"
        - "./scripts/**/*"
        - "./config/**/*"
    inflection/no-plural-filenames:
      - error
    spellcheck/spell-checker:
      - 2
      - comments: true
        strings: true
        identifiers: true
        lang: en_US
        skipWords:
        - api
        - attow
        - camelize
        - cldr
        - com
        - commonjs
        - concat
        - const
        - diff
        - filename
        - formatjs
        - github
        - http
        - https
        - iilei
        - intl
        - javascript
        - js
        - lang
        - mkdirp
        - msg
        - namespace
        - ret
        - src
        - stringify
        - therefor
        - util
        - utils
        - yaml
        - yamljs
        skipIfMatch:
        - ^\S[^aeiou]{1,3}$ # Intl, cldr
          # regarding cldr see https://github.com/aotaduy/eslint-plugin-spellcheck/issues/29
        - https?://[^s]*
