# Styleguide based on airbnb's guide: https://github.com/airbnb/javascript
---
  extends: "airbnb"
  root: true
  ecmaFeatures:
    jsx: true
    templateStrings: true
    classes: true
    modules: true
  parser: "babel-eslint"
  globals:
    - process
  plugins:
    - react
    - inflection
    - getsentry
  settings:
    import/resolver:
      babel-module:
      webpack:
  rules:
    getsentry/jsx-needs-i18n:
      - 1
    no-magic-numbers:
      - error
      -
        ignoreArrayIndexes: true
        ignore:
          - 0
          - 1
    valid-jsdoc:
      - error
    no-alert:
      - error
    no-console:
      - error
    no-return-assign:
      - 0
    react/jsx-no-bind:
      - error
      -
        ignoreRefs: true
    no-debugger:
      - error
    no-underscore-dangle:
      - error
      - allow:
        - __injectIntl
    import/no-extraneous-dependencies:
      - error
      - devDependencies:
        - "**/*.config.js"
        - "**/*.spec.{js,jsx}"
        - "./scripts/**/*"
        - "./config/**/*"
        - "./jestsetup.js"
    inflection/no-plural-filenames:
      - error

